autotestweb/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "appstestcasestastics/:id" ,to: "charts#app_testcase_stastics" , as: "app_testcase_stastics"
  get "projecttestcasestastics/:id" ,to: "charts#project_testcase_stastics" , as: "project_testcase_stastics"
  resources :proxies
  resources :delaytasks
  resources :emails
  resources :emailgroups
  resources :templates
  resources :constants
  get "optimizationlogs", to: "logs#optimizationindex", as: "optimizationindexs"
  resources :logs
  resources :configs
  get "config/svncontent/:id", to: "configs#svncontent", as: "config_svn"
  post "config/updatesvncontent/:id", to: "configs#updatesvncontent", as: "update_config_svn"

  resources :testcases

  get "testcase/getruntestcase", to: "testcases#getruntestcase", as: "get_run_testcase"
  post "testcase/postruntestcase", to: "testcases#postruntestcase", as: "post_run_testcase"
  get "testcase/runtestcaselogs", to: "testcases#runtestcaselogs", as: "run_testcase_logs"

  get "testcase/downloadreport/:id", to: "testcases#downloadreport", as: "download_testcase_report"
  get "get_apps_by_project_id", to: "apps#get_apps_by_project_id", as: "project_id_apps"
  get "get_testcases_by_app_id", to: "testcases#get_testcases_by_app_id", as: "app_id_testcases"
  get "testcase_template(.:format)", to: "testcases#template", as: "download_testcase_template"
  get "testcase/excelupload", to: "testcases#excelupload", as: "testcase_excelupload"
  post "testcase/exceluploadpost", to: "testcases#exceluploadpost", as: "post_testcase_excelupload"
  get "testcase/svncontent/:id", to: "testcases#testcasesvncontent", as: "testcase_svncontent"
  post "testcase/updatesvncontent/:id", to: "testcases#updatetestcasesvncontent", as: "updatetestcase_svncontent"
  get "testcase/errlog/:id", to: "testcases#testcaseerrlog", "as": "testcase_errlog"
  get "gettestcasebycaseid/:caseid", to: "testcases#gettestcasebycaseid"
  resources :servers
  root "apps#index"
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {sessions: "users/sessions", passwords: "users/passwords"}, path_names: {sign_in: "login", sign_out: "logout", password: "secret", confirmation: "verification", unlock: "unblock", registration: "register", sign_up: "cmon_let_me_in"}

  resources :apps
  resources :projects
  get "sendmessage", to: "message#sendmessage", as: "send_message"
  #devise_for :users
  #get "miscellaneous/login",to: "miscellaneous#login",as: :miscellaneous_login
  #get "miscellaneous/register",to: "miscellaneous#register",as: :miscellaneous_register
  #get "miscellaneous/forgot_password",to: "miscellaneous#forgot_password",as: :miscellaneous_forgot_password
  #get "miscellaneous/locked_screen",to: "miscellaneous#locked_screen",as: :miscellaneous_locked_screen
end

autotestweb/app/models/config.rb
class Config < ApplicationRecord
  belongs_to :app
end

autotestweb/app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  include ConfigsHelper
  before_action :set_config, only: [:show, :edit, :update, :destroy]

  # GET /configs
  # GET /configs.json
  def index
    @env = params[:env]

    if @case_type
      @q = Config.where(:env => @env).ransack(params[:q])
    else
      @q = Config.ransack(params[:q])
    end
    @configs = @q.result.page(params[:page])
  end

  # GET /configs/1
  # GET /configs/1.json
  def show
    @svncontent = get_config_content_in_svn @config
  end

  # GET /configs/new
  def new
    @config = Config.new
  end

  # GET /configs/1/edit
  def edit
    @svncontent = get_config_content_in_svn @config
  end

  # POST /configs
  # POST /configs.json
  def create
    @config = Config.new(config_params)
    content = params[:config][:svncontent]
    if content
      update_config_content_in_svn(@config, content)
    end
    respond_to do |format|
      if @config.save
        @recordlog = @config
        format.html { redirect_to @config, notice: "Config was successfully created." }
        format.json { render :show, status: :created, location: @config }
      else
        format.html { render :new }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  def svncontent
    @config = Config.find(params[:id])
    puts @config
    content = get_config_content_in_svn @config
    puts content
    @svncontent = content
  end

  def updatesvncontent
    config = Config.find(params[:id])
    content = params[:config][:svncontent]
    update_config_content_in_svn(config, content)

    redirect_to :action => :svncontent, notice: "修改svn content success"
  end

  # PATCH/PUT /configs/1
  # PATCH/PUT /configs/1.json
  def update
    respond_to do |format|
      if @config.update(config_params)
        content = params[:config][:svncontent]
        if content
          update_config_content_in_svn(@config, content)
        end
        @recordlog = @config
        format.html { redirect_to @config, notice: "Config was successfully updated." }
        format.json { render :show, status: :ok, location: @config }
      else
        format.html { render :edit }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configs/1
  # DELETE /configs/1.json
  def destroy
    @config.destroy
    delete_svn_config_file @config
    @recordlog = @config
    respond_to do |format|
      format.html { redirect_to configs_url, notice: "Config was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_config
    @config = Config.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def config_params
    params.require(:config).permit(:app_id, :name, :description, :env, :content, :casetype)
  end
end

autotestweb/app/helpers/configs_helper.rb
module ConfigsHelper
  include SvnHelper

  def get_config_content_in_svn(config)
    auto_test_url = Rails.application.config.svn_autotest_url
    filename = config.name
    svn_url_base = "#{auto_test_url}/autotestscript"
    path = "#{config.app.project.name}/#{config.app.name}/#{config.casetype}/Config/environments"
    username = Rails.application.config.svn_username
    password = Rails.application.config.svn_password
    get_svn_file_content(path, filename, username, password, svn_url_base)
  end

  def sync_configfile_in_svn
    auto_test_url = Rails.application.config.svn_autotest_url
    svn_url_base = "#{auto_test_url}/autotestscript"
    username = Rails.application.config.svn_username
    password = Rails.application.config.svn_password

    list_svn_dir("", username, password, svn_url_base).split().each do |projectname|
      projectname = projectname.split("/")[-1]
      project = Project.find_by_name(projectname)
      if project
        puts "find projects sync apps"
        list_svn_dir(project.name, username, password, svn_url_base).split().each do |appname|
          appname = appname.split("/")[-1]
          app = App.find_by_name(appname)
          if app
            puts "find app "
          else
            puts "not find it add it "
            app = App.new
            app.name = appname
            app.description = "auto add by script"
            app.project_id = project.id
            app.save!
          end
          apiappfolder = "#{projectname}/#{appname}/api/Config/environments"
          list_svn_dir(apiappfolder, username, password, svn_url_base).split().each do |configfile|
            configenv = configfile.split(".rb")[-1]
            config = Config.where(:app_id => app.id, :env => configenv)
            if config.empty?
              puts "not find needs add"
              config = Config.new
              config.app_id = app.id
              config.name = configfile
              config.env = configenv
              config.casetype = "api"
              config.description = "add by scripts "
              config.save!
            else
              puts "find it skip "
            end

            webappfolder = "#{projectname}/#{appname}/web/Config/environments"
            list_svn_dir(webappfolder, username, password, svn_url_base).split().each do |configfile|
              configenv = configfile.split(".rb")[-1]
              config = Config.where(:app_id => app.id, :env => configenv)
              if config.empty?
                puts "not find needs add"
                config = Config.new
                config.app_id = app.id
                config.name = configfile
                config.env = configenv
                config.casetype = "web"
                config.description = "add by scripts "
                config.save!
              else
                puts "find it skip "
              end
            end
          end
        end
      else
        puts "not find project"
        excludelist = Rails.application.config.autotest_project_exclude
        if excludelist.include? projectname
          puts "find igore projectname"
        else
          project = Project.new
          project.name = projectname
          project.description = "auto add by scripts needs to change manually"
          project.save
        end
      end
    end
  end

  def delete_svn_config_file(config)
    auto_test_url = Rails.application.config.svn_autotest_url
    filename = config.name
    svn_url_base = "#{auto_test_url}/autotestscript"
    path = "#{config.app.project.name}/#{config.app.name}/#{config.casetype}/Config/environments"
    username = Rails.application.config.svn_username
    password = Rails.application.config.svn_password
    delete_svn_file(path, filename, username, password, svn_url_base)
  end

  def update_config_content_in_svn(config, content)
    auto_test_url = Rails.application.config.svn_autotest_url
    filename = config.name
    localfilename = Time.now.strftime("%Y%m%d%H%M%S") + filename
    svn_url_base = "#{auto_test_url}/autotestscript"
    #path = "#{testcase.app.project.name}/#{testcase.app.name}/#{testcase.case_type}/TestCase"
    path = "#{config.app.project.name}/#{config.app.name}/#{config.casetype}/Config/environments"
    username = Rails.application.config.svn_username
    password = Rails.application.config.svn_password
    # write file to local
    File.open(localfilename, "wb") do |f|
      f.write(content)
    end
    # import to svn , needs to delete , before
    #删除远程文件
    delete_svn_file(path, filename, username, password, svn_url_base)
    #创建远程文件
    add_svn_file(path, filename, localfilename, username, password, svn_url_base)
    #删除本地文件
    File.delete(localfilename) if File.exist?(localfilename)
  end
end

autotestweb/app/views/configs/_form.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>配置</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2> <%=title=%></h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <%= form_with(model: config, local: true , class: "form-horizontal m-t") do |form| %>
                  <% if config.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(config.errors.count, "error") %> error</h2>
                      <ul>
                        <% config.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">Name</label>
                    <div class="col-sm-8">
                      <%= form.text_field :name, id: :name ,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">所属应用</label>
                    <div class="col-sm-8">
                      <%= form.select :app_id, (App.all.collect {|p| [p.name, p.id]}) , {:include_blank => false},  id: :app_id , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">环境</label>
                    <div class="col-sm-8">
                      <%= form.select :env, env_list , {:include_blank=> false},  id: :env_id  , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">类型</label>
                    <div class="col-sm-8">
                      <%= form.select :casetype, casetype_list , {:include_blank=> false},  id: :env_id , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">content</label>
                    <div class="col-sm-8">
                      <textarea id="svncontent"  class="form-control" rows="5" name="config[svncontent]"><%= @svncontent%></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">文件描述</label>
                    <div class="col-sm-8">
                      <%= form.text_area :description, id: :description ,:required => true , :class=>"form-control",:rows=>5 %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-3">
                      <% if commit %>
                        <button type="submit" class="btn btn-primary" id="form_submit">
                          提交
                        </button>
                      <%end%>
                      <%= link_to '返回', configs_path , :class=>"btn btn-default" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->
  <script type="text/javascript">
    var editor = CodeMirror.fromTextArea(document.getElementById("svncontent"), {
      mode: "text/x-ruby",
      matchBrackets: true,
      lineNumbers: true,
      extraKeys: {"Ctrl": "autocomplete"},
      indentUnit: 4,
      theme: "rubyblue",
    
    });
  </script>

autotestweb/app/views/configs/edit.html.erb
<%= render 'form', config: @config  , title: "修改配置" , commit: true  %> %>

autotestweb/app/views/configs/index.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>配置</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>配置</h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <div style = "float:left;">
                  <%= button_to '新增配置', new_config_path, method: "get", class: "btn btn-primary" %>
                </div>
                <div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
                  <table>
                    <%= search_form_for @q, url: configs_path(:env => @env)  do |f| %>
                      <input class="form-control" style="display:none" type="search" value="<%=@env%>"  name="env" id="q_case_name_cont" />
                      <td><%= f.search_field :name_or_app_name_cont, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
                      <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
                    <% end %>
                  </table>
                </div>
                <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>应用名</th>
                      <th>配置名</th>
                      <th>环境</th>
                      <th>类型</th>
                      <th colspan="3">操作选项</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @configs.each do |config| %>
                      <tr>
                        <td><%= config.id %></td>
                        <td><%= config.app.name %></td>
                        <td><%= config.name %></td>
                        <td><%= config.env %></td>
                        <td><%= config.casetype %></td>
                        <td><%= link_to '查看', config  , :class=>'label label-info' %></td>
                        <td><%= link_to '修改', edit_config_path(config), :class=>'label label-primary' %></td>
                        <td><%= link_to '删除', config, method: :delete, data: { confirm: 'Are you sure?' } , :class=>'label label-danger'%></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <%= render partial: "layouts/paginator", locals: {zone: @configs} %>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/configs/new.html.erb
<%= render 'form', config: @config , title: "新增配置" , commit: true  %>

autotestweb/app/views/configs/show.html.erb
<%= render 'form', config: @config , title: "查看配置" , commit: false  %>

autotestweb/app/views/configs/svncontent.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>配置文件</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>配置<%= @config.name%></h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <!--start codemirror-->
                <!-- end codemirror -->
                <%= form_with(model: @config, local: true , class: "form-horizontal m-t", url: update_config_svn_path , method: 'POST') do |form| %>
                  <% if @config.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@config.errors.count, "error") %> error</h2>
                      <ul>
                        <% @config.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">content</label>
                    <div class="col-sm-8">
                      <textarea id="svncontent" required="required" class="form-control" rows="5" name="config[svncontent]"><%= @svncontent%></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-3">
                      <button type="submit" class="btn btn-primary" id="form_submit">
                        修改
                      </button>
                      <button type="button" class="btn btn-default" onclick="window.history.back();">
                        返回
                      </button>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->
  
  <script type="text/javascript">
    var editor = CodeMirror.fromTextArea(document.getElementById("svncontent"), {
      mode: "text/x-ruby",
      matchBrackets: true,
      indentUnit: 4
    });
  </script>