autotestweb/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "appstestcasestastics/:id" ,to: "charts#app_testcase_stastics" , as: "app_testcase_stastics"
  get "projecttestcasestastics/:id" ,to: "charts#project_testcase_stastics" , as: "project_testcase_stastics"
  resources :proxies
  resources :delaytasks
  resources :emails
  resources :emailgroups
  resources :templates
  resources :constants
  get "optimizationlogs", to: "logs#optimizationindex", as: "optimizationindexs"
  resources :logs
  resources :configs
  get "config/svncontent/:id", to: "configs#svncontent", as: "config_svn"
  post "config/updatesvncontent/:id", to: "configs#updatesvncontent", as: "update_config_svn"

  resources :testcases

  get "testcase/getruntestcase", to: "testcases#getruntestcase", as: "get_run_testcase"
  post "testcase/postruntestcase", to: "testcases#postruntestcase", as: "post_run_testcase"
  get "testcase/runtestcaselogs", to: "testcases#runtestcaselogs", as: "run_testcase_logs"

  get "testcase/downloadreport/:id", to: "testcases#downloadreport", as: "download_testcase_report"
  get "get_apps_by_project_id", to: "apps#get_apps_by_project_id", as: "project_id_apps"
  get "get_testcases_by_app_id", to: "testcases#get_testcases_by_app_id", as: "app_id_testcases"
  get "testcase_template(.:format)", to: "testcases#template", as: "download_testcase_template"
  get "testcase/excelupload", to: "testcases#excelupload", as: "testcase_excelupload"
  post "testcase/exceluploadpost", to: "testcases#exceluploadpost", as: "post_testcase_excelupload"
  get "testcase/svncontent/:id", to: "testcases#testcasesvncontent", as: "testcase_svncontent"
  post "testcase/updatesvncontent/:id", to: "testcases#updatetestcasesvncontent", as: "updatetestcase_svncontent"
  get "testcase/errlog/:id", to: "testcases#testcaseerrlog", "as": "testcase_errlog"
  get "gettestcasebycaseid/:caseid", to: "testcases#gettestcasebycaseid"
  resources :servers
  root "apps#index"
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {sessions: "users/sessions", passwords: "users/passwords"}, path_names: {sign_in: "login", sign_out: "logout", password: "secret", confirmation: "verification", unlock: "unblock", registration: "register", sign_up: "cmon_let_me_in"}

  resources :apps
  resources :projects
  get "sendmessage", to: "message#sendmessage", as: "send_message"
  #devise_for :users
  #get "miscellaneous/login",to: "miscellaneous#login",as: :miscellaneous_login
  #get "miscellaneous/register",to: "miscellaneous#register",as: :miscellaneous_register
  #get "miscellaneous/forgot_password",to: "miscellaneous#forgot_password",as: :miscellaneous_forgot_password
  #get "miscellaneous/locked_screen",to: "miscellaneous#locked_screen",as: :miscellaneous_locked_screen
end

autotestweb/app/models/server.rb
class Server < ApplicationRecord
  def name
    ip
  end
end

autotestweb/app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @q = Server.ransack(params[:q])

    @servers = @q.result.page(params[:page])
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        @recordlog = @server
        format.html { redirect_to @server, notice: "Server was successfully created." }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        @recordlog = @server
        format.html { redirect_to @server, notice: "Server was successfully updated." }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      @recordlog = @server
      format.html { redirect_to servers_url, notice: "Server was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_server
    @server = Server.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def server_params
    params.require(:server).permit(:ip, :username, :password, :port)
  end
end

autotestweb/app/helpers/servers_helper.rb
module ServersHelper
end

autotestweb/app/views/servers/_form.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>测试服务器</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2> <%=title=%></h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <%= form_with(model: server, local: true , class: "form-horizontal m-t") do |form| %>
                  <% if server.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(server.errors.count, "error") %> error</h2>
                      <ul>
                        <% server.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">IP</label>
                    <div class="col-sm-8">
                      <%= form.text_field :ip, id: :ip ,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">username</label>
                    <div class="col-sm-8">
                      <%= form.text_field :username, id: :username ,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">password</label>
                    <div class="col-sm-8">
                      <%= form.text_field :password, id: :password ,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">port</label>
                    <div class="col-sm-8">
                      <%= form.text_field :port, id: :port,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-3">
                      <% if commit %>
                        <button type="submit" class="btn btn-primary" id="form_submit">
                          提交
                        </button>
                      <%end%>
                      <%= link_to '返回', servers_path , :class=>"btn btn-default" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/servers/edit.html.erb
<%= render 'form', server: @server , title: "修改测试服务器" , commit: true %>

autotestweb/app/views/servers/index.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>测试服务器</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>测试服务器</h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <div style = "float:left;">
                  <%= button_to '新增测试服务器', new_server_path, method: "get", class: "btn btn-primary" %>
                </div>
                <div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
                  <table>
                    <%= search_form_for @q, url: servers_path  do |f| %>
                      <td><%= f.search_field :ip_cont, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
                      <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
                    <% end %>
                  </table>
                </div>
                <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>IP</th>
                      <th>登录名</th>
                      <th>登陆密码</th>
                      <th>登陆PORT</th>
                      <th colspan="3">操作选项</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @servers.each do |server| %>
                      <tr>
                        <td><%= server.id %></td>
                        <td><%= server.ip %></td>
                        <td><%= server.username %></td>
                        <td><%= server.password %></td>
                        <td><%= server.port %></td>
                        <td><%= link_to '查看', server  , :class=>'label label-info' %></td>
                        <td><%= link_to '修改', edit_server_path(server), :class=>'label label-primary' %></td>
                        <td><%= link_to '删除', server, method: :delete, data: { confirm: 'Are you sure?' } , :class=>'label label-danger'%></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <%= render partial: "layouts/paginator", locals: {zone: @servers} %>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/servers/new.html.erb
<%= render 'form', server: @server , title: "新增测试服务器" , commit: true %>

autotestweb/app/views/servers/show.html.erb
<%= render 'form', server: @server , title: "查看测试服务器" , commit: false %>