autotestweb/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "appstestcasestastics/:id" ,to: "charts#app_testcase_stastics" , as: "app_testcase_stastics"
  get "projecttestcasestastics/:id" ,to: "charts#project_testcase_stastics" , as: "project_testcase_stastics"
  resources :proxies
  resources :delaytasks
  resources :emails
  resources :emailgroups
  resources :templates
  resources :constants
  get "optimizationlogs", to: "logs#optimizationindex", as: "optimizationindexs"
  resources :logs
  resources :configs
  get "config/svncontent/:id", to: "configs#svncontent", as: "config_svn"
  post "config/updatesvncontent/:id", to: "configs#updatesvncontent", as: "update_config_svn"

  resources :testcases

  get "testcase/getruntestcase", to: "testcases#getruntestcase", as: "get_run_testcase"
  post "testcase/postruntestcase", to: "testcases#postruntestcase", as: "post_run_testcase"
  get "testcase/runtestcaselogs", to: "testcases#runtestcaselogs", as: "run_testcase_logs"

  get "testcase/downloadreport/:id", to: "testcases#downloadreport", as: "download_testcase_report"
  get "get_apps_by_project_id", to: "apps#get_apps_by_project_id", as: "project_id_apps"
  get "get_testcases_by_app_id", to: "testcases#get_testcases_by_app_id", as: "app_id_testcases"
  get "testcase_template(.:format)", to: "testcases#template", as: "download_testcase_template"
  get "testcase/excelupload", to: "testcases#excelupload", as: "testcase_excelupload"
  post "testcase/exceluploadpost", to: "testcases#exceluploadpost", as: "post_testcase_excelupload"
  get "testcase/svncontent/:id", to: "testcases#testcasesvncontent", as: "testcase_svncontent"
  post "testcase/updatesvncontent/:id", to: "testcases#updatetestcasesvncontent", as: "updatetestcase_svncontent"
  get "testcase/errlog/:id", to: "testcases#testcaseerrlog", "as": "testcase_errlog"
  get "gettestcasebycaseid/:caseid", to: "testcases#gettestcasebycaseid"
  resources :servers
  root "apps#index"
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {sessions: "users/sessions", passwords: "users/passwords"}, path_names: {sign_in: "login", sign_out: "logout", password: "secret", confirmation: "verification", unlock: "unblock", registration: "register", sign_up: "cmon_let_me_in"}

  resources :apps
  resources :projects
  get "sendmessage", to: "message#sendmessage", as: "send_message"
  #devise_for :users
  #get "miscellaneous/login",to: "miscellaneous#login",as: :miscellaneous_login
  #get "miscellaneous/register",to: "miscellaneous#register",as: :miscellaneous_register
  #get "miscellaneous/forgot_password",to: "miscellaneous#forgot_password",as: :miscellaneous_forgot_password
  #get "miscellaneous/locked_screen",to: "miscellaneous#locked_screen",as: :miscellaneous_locked_screen
end

autotestweb/app/models/log.rb
class Log < ApplicationRecord
  def name
  end
end

autotestweb/app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @q = Log.order("id desc ").ransack(params[:q])
    @logs = @q.result.page(params[:page])
  end

  def optimizationindex
    @q = Log.order("id desc ").ransack(params[:q])
    @logs = @q.result.page(params[:page])
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: "Log was successfully created." }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_log
    @log = Log.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def log_params
    params.require(:log).permit(:controller, :action, :user, :params, :objid, :method)
  end
end

autotestweb/app/helpers/logs_helper.rb
module LogsHelper
end

autotestweb/app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :controller %>
    <%= form.text_field :controller %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :params %>
    <%= form.text_area :params %>
  </div>

  <div class="field">
    <%= form.label :objid %>
    <%= form.number_field :objid %>
  </div>

  <div class="field">
    <%= form.label :method %>
    <%= form.text_field :method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

autotestweb/app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

autotestweb/app/views/logs/index.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>操作日志</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>操作日志</h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
                  <table>
                    <%= search_form_for @q, url: logs_path do |f| %>
                      <td><%= f.search_field :controller_or_action_or_method_cont, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
                      <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
                    <% end %>
                  </table>
                </div>
                <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Controller</th>
                      <th>Action</th>
                      <th>User</th>
                      <th>Method</th>
                      <th>Model</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @logs.each do |log| %>
                      <tr>
                        <td><%= log.id %></td>

                        <td><%= log.controller %></td>
                        <td><%= log.action %></td>
                        <td><%= log.user %></td>
                        <td><%= log.method %></td>
                        <td><%= log.modelclass %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <%= render partial: "layouts/paginator", locals: {zone: @logs} %>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

autotestweb/app/views/logs/optimizationindex.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>操作日志</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>操作日志</h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
                  <table>
                    <%= search_form_for @q, url: optimizationindexs_path do |f| %>
                      <td><%= f.search_field :objname_cont, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
                      <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
                    <% end %>
                  </table>
                </div>
                <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>User</th>
                      <th>Action</th>
                      <th>Model</th> 
                      <th>modelname </th>
                      <th>time </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @logs.each do |log| %>
                      <tr>
                        <td><%= log.id %></td>
                        <td><%= log.user %></td>
                        <td><%= Constant.find_by_name_and_scope( log.action ,"Action" ) %></td>
                        <td><%= Constant.find_by_name_and_scope( log.modelclass ,"Model" ) %></td>
                        <td><%= log.objname %></td> 
                        <td><%= log.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td> 
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <%= render partial: "layouts/paginator", locals: {zone: @logs} %>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Controller:</strong>
  <%= @log.controller %>
</p>

<p>
  <strong>Action:</strong>
  <%= @log.action %>
</p>

<p>
  <strong>User:</strong>
  <%= @log.user %>
</p>

<p>
  <strong>Params:</strong>
  <%= @log.params %>
</p>

<p>
  <strong>Objid:</strong>
  <%= @log.objid %>
</p>

<p>
  <strong>Method:</strong>
  <%= @log.method %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>