autotestweb/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "appstestcasestastics/:id" ,to: "charts#app_testcase_stastics" , as: "app_testcase_stastics"
  get "projecttestcasestastics/:id" ,to: "charts#project_testcase_stastics" , as: "project_testcase_stastics"
  resources :proxies
  resources :delaytasks
  resources :emails
  resources :emailgroups
  resources :templates
  resources :constants
  get "optimizationlogs", to: "logs#optimizationindex", as: "optimizationindexs"
  resources :logs
  resources :configs
  get "config/svncontent/:id", to: "configs#svncontent", as: "config_svn"
  post "config/updatesvncontent/:id", to: "configs#updatesvncontent", as: "update_config_svn"

  resources :testcases

  get "testcase/getruntestcase", to: "testcases#getruntestcase", as: "get_run_testcase"
  post "testcase/postruntestcase", to: "testcases#postruntestcase", as: "post_run_testcase"
  get "testcase/runtestcaselogs", to: "testcases#runtestcaselogs", as: "run_testcase_logs"

  get "testcase/downloadreport/:id", to: "testcases#downloadreport", as: "download_testcase_report"
  get "get_apps_by_project_id", to: "apps#get_apps_by_project_id", as: "project_id_apps"
  get "get_testcases_by_app_id", to: "testcases#get_testcases_by_app_id", as: "app_id_testcases"
  get "testcase_template(.:format)", to: "testcases#template", as: "download_testcase_template"
  get "testcase/excelupload", to: "testcases#excelupload", as: "testcase_excelupload"
  post "testcase/exceluploadpost", to: "testcases#exceluploadpost", as: "post_testcase_excelupload"
  get "testcase/svncontent/:id", to: "testcases#testcasesvncontent", as: "testcase_svncontent"
  post "testcase/updatesvncontent/:id", to: "testcases#updatetestcasesvncontent", as: "updatetestcase_svncontent"
  get "testcase/errlog/:id", to: "testcases#testcaseerrlog", "as": "testcase_errlog"
  get "gettestcasebycaseid/:caseid", to: "testcases#gettestcasebycaseid"
  resources :servers
  root "apps#index"
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {sessions: "users/sessions", passwords: "users/passwords"}, path_names: {sign_in: "login", sign_out: "logout", password: "secret", confirmation: "verification", unlock: "unblock", registration: "register", sign_up: "cmon_let_me_in"}

  resources :apps
  resources :projects
  get "sendmessage", to: "message#sendmessage", as: "send_message"
  #devise_for :users
  #get "miscellaneous/login",to: "miscellaneous#login",as: :miscellaneous_login
  #get "miscellaneous/register",to: "miscellaneous#register",as: :miscellaneous_register
  #get "miscellaneous/forgot_password",to: "miscellaneous#forgot_password",as: :miscellaneous_forgot_password
  #get "miscellaneous/locked_screen",to: "miscellaneous#locked_screen",as: :miscellaneous_locked_screen
end

autotestweb/app/models/app.rb
class App < ApplicationRecord
  belongs_to :project
end

autotestweb/app/models/config.rb
class Config < ApplicationRecord
  belongs_to :app
end

autotestweb/app/models/constant.rb
class Constant < ApplicationRecord
  def to_s
    value
  end
end

autotestweb/app/models/delaytask.rb
class Delaytask < ApplicationRecord
end

autotestweb/app/models/email.rb
class Email < ApplicationRecord
  has_many :email_group_and_emails
  has_many :emailgroups , :through => :email_group_and_emails


end

autotestweb/app/models/emailgroup.rb
class Emailgroup < ApplicationRecord
  has_many :email_group_and_emails
  has_many :emails ,  :through => :email_group_and_emails
end

autotestweb/app/models/log.rb
class Log < ApplicationRecord
  def name
  end
end

autotestweb/app/models/project.rb
class Project < ApplicationRecord
  has_many :apps
end

autotestweb/app/models/proxy.rb
class Proxy < ApplicationRecord
end

autotestweb/app/models/runtestcase.rb
class Runtestcase < ApplicationRecord
  def name
    appx = App.find_by_name(app)
    if appx
      appx.name
    else
      "app deleted"
    end
  end
end

autotestweb/app/models/server.rb
class Server < ApplicationRecord
  def name
    ip
  end
end

autotestweb/app/models/template.rb
class Template < ApplicationRecord
end

autotestweb/app/models/testcase.rb
class Testcase < ApplicationRecord
  belongs_to :app, optional: true
  validates_uniqueness_of :case_id

  def name
    case_name
  end
end

autotestweb/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
  end
end

autotestweb/app/helpers/apps_helper.rb
module AppsHelper
end

autotestweb/app/helpers/charts_helper.rb
module ChartsHelper
  def app_testcase_chart_status(app)
    Runtestcase.where(:app => app.name).group(:app, :reportstatus, :user).order("count_id desc").count("id")
  end

  def project_testcase_chart_status(project)
    appnames = project.apps.collect &:name
    Runtestcase.where(:app => appnames).group(:app, :reportstatus ).order("count_id desc").count("id")
  end

  def all_testcase_chart_status 

    Runtestcase.group(:app, :reportstatus, :user).order("count_id desc").count("id")
  end

end

autotestweb/app/helpers/emails_helper.rb
module EmailsHelper
end

autotestweb/app/helpers/logs_helper.rb
module LogsHelper
end

autotestweb/app/helpers/ssh_helper.rb
module SshHelper
  def run(host, username, password, port, cmd, &block)
    Net::SSH.start(host, username, :password => password, :port => port) do |ssh|
      channel = ssh.open_channel do |ch|
        ch.exec cmd do |ch, success|
          raise "could not execute command #{cmd}" unless success

          ch.on_data do |c, data|
            $stdout.print data
            block.call data if block_given?
          end

          ch.on_extended_data do |c, type, data|
            $stderr.print data
            block.call data if block_given?
          end

          ch.on_close { puts "done!" }
        end
      end

      channel.wait
    end
  end

  def copyfile(host, username, password, port, sourcefile, destfile)
    Net::SFTP.start(host, username, :password => password, :port => port) do |sftp|
      sftp.download!(sourcefile, destfile)
    end
  end
end

autotestweb/app/helpers/svn_helper.rb
module SvnHelper
  def get_svn_file_content(path, filename, username, password, svn_url_base)
    `svn  cat #{svn_url_base}/#{path}/#{filename}  --username #{username} --password #{password} --no-auth-cache`
  end

  def delete_svn_file(path, filename, username, password, svn_url_base)
    `svn  delete #{svn_url_base}/#{path}/#{filename}  --username #{username} --password #{password} --no-auth-cache -m "delete svn file"`
  end

  def add_svn_file(path, remotefilename, localfilename, username, password, svn_url_base)
    command = "svn import -m \"add svn file\" #{localfilename}    #{svn_url_base}/#{path}/#{remotefilename} --username #{username} --password #{password} --no-auth-cache --force"
    `#{command}`
  end

  def list_svn_dir(path, username, password, svn_url_base)
    command = "svn ls  #{svn_url_base}/#{path} --username #{username} --password #{password} --no-auth-cache "
    `#{command}`
  end

  def svn_file_exist?(path, remotefilename, username, password, svn_url_base)
    command = "svn info   #{svn_url_base}/#{path}/#{remotefilename} --username #{username} --password #{password} --no-auth-cache "
    result = `#{command}`
    if result =~ /E200009/i
      false
    else
      if result.empty?
        false
      else
        true
      end
    end
  end
end

autotestweb/app/views/apps/_form.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>应用</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2> <%=title=%></h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <%= form_with(model: app, local: true , class: "form-horizontal m-t") do |form| %>
                  <% if app.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(app.errors.count, "error") %> error</h2>
                      <ul>
                        <% app.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">应用名</label>
                    <div class="col-sm-8">
                      <%= form.text_field :name, id: :name ,:required => true , :class=>"form-control" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">所属项目</label>
                    <div class="col-sm-8">
                      <%= form.select :project_id, (Project.all.collect {|p| [p.name, p.id]}) , {},  id: :project_id ,:required => true , :class=>"form-control", :include_blank => false %>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-3 control-label">应用描述</label>
                    <div class="col-sm-8">
                      <%= form.text_area :description, id: :description ,:required => true , :class=>"form-control",:rows=>5 %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-3">
                      <% if commit %>
                        <button type="submit" class="btn btn-primary" id="form_submit">
                          提交
                        </button>
                      <%end%>
                      <%= link_to '返回', apps_path , :class=>"btn btn-default" %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/apps/edit.html.erb
<%= render 'form', app: @app , title: "修改应用" , commit: true %>

autotestweb/app/views/apps/index.html.erb
<% content_for :body_class do %>
<% end%>
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>首页</li>
      <li>应用</li>
    </ol>
  </div>
  <!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <p id="notice"><%= notice %></p>
    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>应用</h2>
          </header>
          <!-- widget div-->
          <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
              <div class="table-responsive">
                <div style = "float:left;">
                  <%= button_to '新增应用', new_app_path, method: "get", class: "btn btn-primary" %>
                </div>
                <div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
                  <table>
                    <%= search_form_for @q, url: apps_path  do |f| %>
                      <td><%= f.search_field :name_cont, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
                      <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
                    <% end %>
                  </table>
                </div>
                <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>项目名</th>
                      <th>应用</th>
                      <th>描述</th>
                      <th colspan="4">操作选项</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @apps.each do |app| %>
                      <tr>
                        <td><%= app.id %></td>
                        <td><%= app.name %></td>
                        <td><%= app.project.name %></td>
                        <td><%= app.description %></td>
                        <td><%= link_to '查看', app  , :class=>'label label-info' %></td>
                        <td><%= link_to '修改', edit_app_path(app), :class=>'label label-primary' %></td>
                        <td><%= link_to '用例执行统计', app_testcase_stastics_path(app), :class=>'label label-success' %></td>
                        <td><%= link_to '删除', app, method: :delete, data: { confirm: 'Are you sure?' } , :class=>'label label-danger'%></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <%= render partial: "layouts/paginator", locals: {zone: @apps} %>
            <!-- end widget content -->
          </div>
          <!-- end widget div -->
        </div>
        <!-- end widget -->
      </div>
      <!-- end row -->
    </section>
    <!-- end widget grid -->
  </div>
  <!-- END MAIN CONTENT -->

autotestweb/app/views/apps/new.html.erb
<%= render 'form', app: @app , title: "新增应用" , commit: true %>

autotestweb/app/views/apps/show.html.erb
<%= render 'form', app: @app , title: "查看应用" , commit: false %>

autotestweb/app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <span class="txt-color-white"><span class="hidden-xs"> - 自动化测试平台</span> © 2017-2018</span>
    </div>

    <div class="col-xs-6 col-sm-6 text-right hidden-xs">
    </div>
  </div>
</div>

autotestweb/app/views/layouts/_header.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <a href="/"><span id="logo"><h4><label> 自动化测试</label></h4></span></a>
    <!-- END LOGO PLACEHOLDER -->
  </div>
  <%= yield :top_right %>

  <% if current_user %>
    <!-- pulled right: nav area -->
    <div class="pull-right">

      <!-- logout button -->
      <div id="logout" class="btn-header transparent pull-right">
        <span>
          <%= link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'} ,:method=>'delete')  do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </span>
      </div>
      <!-- end logout button -->


    </div>
    <!-- end pulled right: nav area -->
  <% end %>

</header>

autotestweb/app/views/layouts/_left_panel.html.erb
<aside id="left-panel">
  <!-- User info -->
  <div class="login-info">
    <span> <!-- User image size is adjusted inside CSS, it should stay as it -->
      <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
        <%= image_tag 'avatars/sunny.png', alt: 'me', class: 'online' %>
        <span>
          <%= current_user.email%>
        </span>
      </a>
    </span>
  </div>
  <!-- end user info -->
  <!-- NAVIGATION : This navigation is also responsive-->
  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->
    <ul>
      <%= left_menu %>
      <li class="chat-users">
        <a href="#"><i class="fa fa-lg fa-fw fa-comment-o"><em class="bg-color-pink flash animated">!</em></i> <span class="menu-item-parent">Chat</span></a>
        <ul>
          <li>
            <!-- DISPLAY USERS -->
            <div class="display-users">
              <input class="form-control chat-user-filter" placeholder="Filter" type="text">
              <%User.all.each do |user|%>
                <div id = "divchatbox-<%= user.id%>"> </div>
                <a href="javascript:void(0)" class="usr"  id="<%= user.id%>" onclick = 'addchatbox(this,"<%=user.email%>" ,"<%=current_user.email%>")' >
                    <i></i><%= user.email%>
            </a> 
          <% end%>
          <!-- extra -->

          <!-- extra end-->

      </div>
      <!-- END DISPLAY USERS -->
    </li>
  </ul>
</li>
</ul>
</nav>
</aside>

<script>
 // add chat plugin function
 function addchatbox(obj , sendemail ,  currentemail){
  var addid = "divchatbox-" + obj.id.toString();
  var chatboxdivid = "#divchatbox-" + obj.id.toString();  
  if( $(chatboxdivid).hasClass("initi")) {
    //$(chatboxdivid).chatbox("option", "boxManager").toggleBox();
   $(chatboxdivid).closest(".ui-chatbox").show();

  } else{
    $(chatboxdivid).chatbox({id: addid, 
      user:{key : sendemail},
      title : sendemail ,
      messageSent : function(id, user, msg) {
          $.get("/sendmessage?message=" + msg + "&sendemail=" + sendemail + "&displaydiv=" + addid , function(result){
            $(chatboxdivid).chatbox("option", "boxManager").addMsg(currentemail, msg);
          });
        }


    });
    $(chatboxdivid).addClass("initi"); 
    $(chatboxdivid).closest(".ui-chatbox").show(); 
  }
 } 
 //$("#togglea").chatbox("option", "boxManager").toggleBox();
</script>

autotestweb/app/views/layouts/_paginator.html.erb
<div style="float:left; display:inline"><%= page_entries_info zone %></div>
<div style="float:right; display:inline"><%= paginate zone ,theme: 'bootstrap3',window: 4, outer_window: 3 %></div>

autotestweb/app/views/layouts/_rabbon_menu.html.erb
<div id="ribbon">
  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li>首页</li>
  </ol>
  <div id="message" style="float: right;"></div>
  <!-- end breadcrumb -->

  <!-- You can also add more buttons to the
  ribbon for further usability

  Example below:

  <span class="ribbon-button-alignment pull-right">
  <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
  <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
  <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
  </span> -->

</div>

autotestweb/app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    pageSetUp();

  })
</script>

autotestweb/app/views/layouts/_search.html.erb
<div class="form-inline input-group input-group-sm" style="float:right; margin-left:50px;">
  <table>
    <% if url%>
      <%= search_form_for @q do |f| %>
        <td><%= f.search_field zone, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
        <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
      <%end%>
    <%else%>
      <%= search_form_for @q, url: url do |f| %>
        <td><%= f.search_field zone, class: "form-control", style: "border:1px solid #C0C0C0" %></td>
        <td><span class="input-group-btn"><%= f.submit class: "btn btn-primary" %></span></td>
      <%end%>
    <% end %>
  </table>
</div>

autotestweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autotestweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="current-user" id="<%= current_user.try(:id) %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      .realtimelog {
        height: 500px;
          overflow-y: auto;
        }
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:scripts).present? ? yield(:scripts) : render(partial: 'layouts/scripts') %>
  </head>
  <!-- body_class 用来调整样式 -->
  <body class="<%= yield :body_class %>">
    <!-- HEADER -->
    <%= render partial: 'layouts/header' %>
    <!-- END HEADER -->
    <!-- Left panel : Navigation area -->
    <!-- Note: This width of the aside area can be adjusted through LESS variables -->
    <%= render partial: 'layouts/left_panel' if current_user  %>
    <!-- END NAVIGATION -->
    <!-- MAIN PANEL -->
    <div id="main" role="main">
      <%= yield :ribbon %>
      <div id="publicmessage" style="margin:20px;display:none">
        <!-- widget grid -->
        <section id="widget-grid" class="">
          <!-- row -->
          <div class="row">
            <!-- NEW WIDGET START -->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
              <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>realtime日志</h2>
              </header>
              <!-- widget div-->
              <div>
                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                  <!-- This area used as dropdown edit box -->
                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body">
                  <a class="btn btn-danger" data-method="get" href="#" onclick="window.location.reload()">返回</a>
                  <pre id = "realtimelog" class="realtimelog"></pre>
                </div>
                <!-- end widget content -->
              </div>
              <!-- end widget div -->
            </div>
            <!-- end widget -->
          </div>
          <!-- end row -->
        </section>
        <!-- end widget grid -->
      </div>
      <div id="deploymessage" style="margin:20px;display:none">
        <!-- widget grid -->
        <section id="widget-grid" class="">
          <!-- row -->
          <div class="row">
            <!-- NEW WIDGET START -->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
              <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>deploy message日志</h2>
              </header>
              <!-- widget div-->
              <div>
                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                  <!-- This area used as dropdown edit box -->
                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body" id= "deploymessagecontent">
                  <a class="btn btn-danger" data-method="get" href="#" onclick="window.location.reload()">返回</a>
                  <!-- pre id = "realtimelog" class="realtimelog"></pre -->
                </div>
                <!-- end widget content -->
              </div>
              <!-- end widget div -->
            </div>
            <!-- end widget -->
          </div>
          <!-- end row -->
        </section>
        <!-- end widget grid -->
      </div>
      <div id="privatemessage" style="margin:20px;display:none" >
        <!-- widget grid -->
        <section id="widget-grid" class="">
          <!-- row -->
          <div class="row">
            <!-- NEW WIDGET START -->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
              <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>realtime日志</h2>
              </header>
              <!-- widget div-->
              <div>
                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                  <!-- This area used as dropdown edit box -->
                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body">
                  <a class="btn btn-danger" data-method="get" href="#" onclick="window.location.reload()">返回</a>
                  <pre id = "privaterealtimelog" class="realtimelog"></pre>
                </div>
                <!-- end widget content -->
              </div>
              <!-- end widget div -->
            </div>
            <!-- end widget -->
          </div>
          <!-- end row -->
        </section>
        <!-- end widget grid -->
      </div>
      <% if notice %>
        <div class="alert alert-success fade in">
          <button data-dismiss="alert" class="close">
            ×
          </button>
          <i class="fa-fw fa fa-check"></i>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning fade in">
          <button data-dismiss="alert" class="close">
            ×
          </button>
          <i class="fa-fw fa fa-warning"></i>
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
      <!-- chat ui for websocket -->
      <!--div class="demo" id="chatdiv">
        <span id="demo-setting" onclick="displaychat()">chat</span>  </button>
        <form>
           <div> <input name="xxx" value="xxx"/> </div>
           <div ><a> yyy </a> </div>
           <div ><a> xxx </a> </div>
         </form>
       </div>
    </div>--

    <!-- end chat system-->
      <div id="chat_div"></div>
    </div>
    <!-- END MAIN PANEL -->
    <!-- PAGE FOOTER -->
    <%= render partial: 'layouts/footer' if current_user  %>
    <!-- END PAGE FOOTER -->
  </body>
  <script type="text/javascript">
    $(function() {
        // in app.js ,需要精简
        // pageSetUp();
        var left_m1=$("li.open span.menu-item-parent:first");
        var left_m2=$("li.open ul li.active span.menu-item-parent");
        if(left_m1.text() != ""){
          $("ol.breadcrumb").append("<li>" + left_m1.text() +"</li>");
        }
        if(left_m1.text() != ""){
          $("ol.breadcrumb").append("<li>" + left_m2.text() +"</li>");
        }
    
    })
    
    function displaychat(){
      if ($("#chatdiv").hasClass("activate")){
        $("#chatdiv").removeClass("activate");
    
      } else{
        $("#chatdiv").addClass("activate");
      }
    }
      $("#chat_divxxxx").chatbox({id:"chat_div",
    	user:{key : "value"},
    	title : "test chat",
    	messageSent : function(id, user, msg) {
    	  $("#log").append(id + " said: " + msg + "<br/>");
    	  $("#chat_div").chatbox("option", "boxManager").addMsg(id, msg);
    	}
      });
  </script>
</html>